export const leads = [
  {
    id: 1,
    name: "Jana",
    company: "Ben Technology",
    phone: "+91 8149622635 ",
    email: "jana@bolt.com",
    status: "Qualified",
    source: "LinkedIn",
    notes: "Requested a product demo",
  },
  {
    id: 2,
    name: "Spencer Johnson",
    company: "Tech Solutions",
    phone: "+91 9597103089 ",
    email: "spencer@tech.com",
    status: "Contacted",
    source: "Website",
   notes: "Follow up next week",
  },
  {
    id: 3,
    name: "Michael",
    company: "One 8",
    phone: "+91 8956855775 ",
    email: "michael@growth.com",
    status: "New",
    source: "Referral",
    notes: "Requested a product demo",
  },
  {
    id: 4,
    name: "Rohit",
    company: "One 8",
    phone: "+91 3595482625 ",
    email: "rohit@mail.com",
    status: "Contacted",
    source: "Referral",
   notes: "Budget approval pending",
  },
  {
    id: 5,
    name: "Rahul",
    company: "Skyline Solutions",
    phone: "+91 9876543203",
    email: "rahul verma@mail.com",
    status: "Proposal",
    source: "Referral",
    notes: "Awaiting management approval",
  },
  {
    id: 6,
    name: "Aarav Sharma",
    company: "TechNova Solutions",
    phone: "+91 9876543201",
    email: "aarav.sharma@mail.com",
    status: "New",
    source: "Website",
    notes: "Interested in CRM software",
  },
  {
    id: 7,
    name: "Priya Nair",
    company: "BlueWave Technologies",
    phone: "+91 9876543202",
    email: "priya.nair@mail.com",
    status: "Contacted",
    source: "LinkedIn",
    notes: "Requested product demo",
  },
  {
    id: 8,
    name: "Rahul Verma",
    company: "Skyline Solutions",
    phone: "+91 9876543203",
    email: "rahul.verma@mail.com",
    status: "Proposal",
    source: "Referral",
    notes: "Awaiting management approval",
  },
  {
    id: 9,
    name: "Sneha Reddy",
    company: "NextGen Systems",
    phone: "+91 9876543204",
    email: "sneha.reddy@mail.com",
    status: "Qualified",
    source: "Website",
    notes: "Interested in enterprise plan",
  },
  {
    id: 10,
    name: "Vikram Singh",
    company: "InnovateX",
    phone: "+91 9876543205",
    email: "vikram.singh@mail.com",
    status: "New",
    source: "Cold Call",
    notes: "Needs pricing details",
  },
  {
    id: 11,
    name: "Ananya Gupta",
    company: "DigitalSphere",
    phone: "+91 9876543206",
    email: "ananya.gupta@mail.com",
    status: "Contacted",
    source: "Referral",
    notes: "Follow-up next week",
  },
  {
    id: 12,
    name: "Karthik Raj",
    company: "CloudEdge",
    phone: "+91 9876543207",
    email: "karthik.raj@mail.com",
    status: "Qualified",
    source: "LinkedIn",
    notes: "Budget approved",
  },
  {
    id: 13,
    name: "Meera Joshi",
    company: "SmartWorks Pvt Ltd",
    phone: "+91 9876543208",
    email: "meera.joshi@mail.com",
    status: "Proposal",
    source: "Website",
    notes: "Proposal sent",
  },
  {
    id: 14,
    name: "Arjun Patel",
    company: "Vertex Labs",
    phone: "+91 9876543209",
    email: "arjun.patel@mail.com",
    status: "New",
    source: "Event",
    notes: "Met at conference",
  },
  {
    id: 15,
    name: "Riya Mehta",
    company: "Visionary Tech",
    phone: "+91 9876543210",
    email: "riya.mehta@mail.com",
    status: "Contacted",
    source: "Website",
    notes: "Requested callback",
  },
  {
    id: 16,
    name: "Aditya Sharma",
    company: "FutureSoft",
    phone: "+91 9876543211",
    email: "aditya.sharma@mail.com",
    status: "Qualified",
    source: "Referral",
    notes: "Interested in premium plan",
  },
  {
    id: 17,
    name: "Pooja Verma",
    company: "CodeCraft Solutions",
    phone: "+91 9876543212",
    email: "pooja.verma@mail.com",
    status: "Proposal",
    source: "LinkedIn",
    notes: "Waiting for response",
  },
  {
    id: 18,
    name: "Sai Krishna",
    company: "Alpha Innovations",
    phone: "+91 9876543213",
    email: "sai.krishna@mail.com",
    status: "New",
    source: "Cold Email",
    notes: "Lead generated recently",
  },
  {
    id: 19,
    name: "Kavya Iyer",
    company: "BrightPath Technologies",
    phone: "+91 9876543214",
    email: "kavya.iyer@mail.com",
    status: "Contacted",
    source: "Website",
    notes: "Asked for demo",
  },
  {
    id: 20,
    name: "Nikhil Kumar",
    company: "Quantum Systems",
    phone: "+91 9876543215",
    email: "nikhil.kumar@mail.com",
    status: "Qualified",
    source: "Referral",
    notes: "Decision maker identified",
  },
  {
    id: 21,
    name: "Deepika Rao",
    company: "CoreTech Solutions",
    phone: "+91 9876543216",
    email: "deepika.rao@mail.com",
    status: "Proposal",
    source: "Website",
    notes: "Proposal under review",
  },
  {
    id: 22,
    name: "Rohit Menon",
    company: "DataBridge",
    phone: "+91 9876543217",
    email: "rohit.menon@mail.com",
    status: "New",
    source: "Cold Call",
    notes: "First contact pending",
  },
  {
    id: 23,
    name: "Neha Kapoor",
    company: "Spark Digital",
    phone: "+91 9876543218",
    email: "neha.kapoor@mail.com",
    status: "Contacted",
    source: "Event",
    notes: "Demo scheduled",
  },
  {
    id: 24,
    name: "Manoj Bhat",
    company: "Elevate Tech",
    phone: "+91 9876543219",
    email: "manoj.bhat@mail.com",
    status: "Qualified",
    source: "LinkedIn",
    notes: "Ready for proposal",
  },
  {
    id: 25,
    name: "Aishwarya Nair",
    company: "Zenith Solutions",
    phone: "+91 9876543220",
    email: "aishwarya.nair@mail.com",
    status: "Proposal",
    source: "Website",
    notes: "Awaiting final approval",
  },
  {
  id: 26,
  name: "Harish Kumar",
  company: "NovaTech Solutions",
  phone: "+91 9876543226",
  email: "harish.kumar@mail.com",
  status: "Qualified",
  source: "LinkedIn",
  notes: "Requested product brochure",
 },
 {
  id: 27,
  name: "Divya Sharma",
  company: "TechBridge Pvt Ltd",
  phone: "+91 9876543227",
  email: "divya.sharma@mail.com",
  status: "Qualified",
  source: "Website",
  notes: "Follow-up call scheduled",
 },
 {
  id: 28,
  name: "Rakesh Verma",
  company: "CloudSync Technologies",
  phone: "+91 9876543228",
  email: "rakesh.verma@mail.com",
  status: "Contacted",
  source: "Referral",
  notes: "Interested in premium plan",
 },
 {
  id: 29,
  name: "Swathi Reddy",
  company: "VisionTech Solutions",
  phone: "+91 9876543229",
  email: "swathi.reddy@mail.com",
  status: "Contacted",
  source: "Event",
  notes: "Demo discussion completed",
 },
 {
  id: 30,
  name: "Ajay Patel",
  company: "FutureWorks",
  phone: "+91 9876543230",
  email: "ajay.patel@mail.com",
  status: "Qualified",
  source: "Cold Email",
  notes: "Awaiting feedback",
 },
 {
  id: 31,
  name: "Keerthana Iyer",
  company: "SmartEdge Systems",
  phone: "+91 9876543231",
  email: "keerthana.iyer@mail.com",
  status: "Qualified",
  source: "Website",
  notes: "Requested pricing details",
 },
 {
  id: 32,
  name: "Sanjay Nair",
  company: "AlphaCore Technologies",
  phone: "+91 9876543232",
  email: "sanjay.nair@mail.com",
  status: "Qualified",
  source: "LinkedIn",
  notes: "Budget approved",
 },
 {
  id: 33,
  name: "Pavithra Raj",
  company: "DigitalNest",
  phone: "+91 9876543233",
  email: "pavithra.raj@mail.com",
  status: "Qualified",
  source: "Referral",
  notes: "Ready for proposal",
 },
 {
  id: 34,
  name: "Arvind Kumar",
  company: "ZenSoft Solutions",
  phone: "+91 9876543234",
  email: "arvind.kumar@mail.com",
  status: "New",
  source: "Website",
  notes: "Recently signed up",
 },
 {
  id: 35,
  name: "Nandhini Prakash",
  company: "BrightFuture Tech",
  phone: "+91 9876543235",
  email: "nandhini.prakash@mail.com",
  status: "Qualified",
  source: "LinkedIn",
  notes: "Proposal sent for review",
 },
];